services:
  comfyui-worker:
    image: local/runpod-worker-comfy:dev-sdxl  # Your locally built image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
      - IMAGE_RETURN_METHOD=azure
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=kimaratestrunpod
      - COMFY_POLLING_INTERVAL_MS=250
      - COMFY_POLLING_MAX_RETRIES=500
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./test_data/output:/comfyui/output
      - ./test_data/volume:/runpod-volume