name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: df -h
      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo rm -rf ~/.cache/
          sudo apt-get clean
      - run: df -h

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update the ToC in the README.md
        run: npx markdown-toc README.md -i

      - name: Semantic release
        uses: codfish/semantic-release-action@v3
        id: semanticrelease
        with:
          additional-packages: |
            ['@semantic-release/git', '@semantic-release/changelog', '@semantic-release/exec']
        env:
          GITHUB_TOKEN: ${{ secrets.KIMARA_SEMANTIC_RELEASE }}

      - name: Set environment variables
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        run: |
          echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_REPO }}" >> $GITHUB_ENV
          echo "DOCKERHUB_IMG=${{ vars.DOCKERHUB_IMG }}" >> $GITHUB_ENV
          echo "HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ steps.semanticrelease.outputs.release-version }}" >> $GITHUB_ENV

      - name: Build and push the images to Docker Hub
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        uses: docker/bake-action@v2
        with:
          push: true
          set: |
            *.args.DOCKERHUB_REPO=${{ env.DOCKERHUB_REPO }}
            *.args.DOCKERHUB_IMG=${{ env.DOCKERHUB_IMG }}
            *.args.RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            *.args.HUGGINGFACE_ACCESS_TOKEN=${{ env.HUGGINGFACE_ACCESS_TOKEN }}

      - name: Update description on Docker Hub
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
          enable-url-completion: true
          
      # Pull the base image that was already pushed
      - name: Pull base image for slimming
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        run: |
          docker pull ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}:${{ env.RELEASE_VERSION }}-base

      - name: Run DockerSlim to optimize image
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        id: slim
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
          DSLIM_CONTINUE_AFTER: 10
          DSLIM_EXPOSE: 8188
          DSLIM_RC_CMD: "/start.sh"
          DSLIM_INCLUDE_PATH: "/comfyui,/opt/venv,/usr/lib/python3.11,/usr/lib/python3,/usr/local/lib/python3.11,/start.sh,/restore_snapshot.sh,/rp_handler.py,/test_input.json,/extra_model_paths.yaml,/models"
          DSLIM_INCLUDE_SHELL: true
          DSLIM_INCLUDE_ZONEINFO: true
          DSLIM_RM_FILE_ARTIFACTS: true
          DSLIM_SHOW_BLOGS: true
          DSLIM_SHOW_CLOGS: true
        with:
          target: ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}:${{ env.RELEASE_VERSION }}-base
          tag: "slim"

      - name: Show slim build report
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        run: |
          echo "Slim build report:"
          echo "${{ steps.slim.outputs.report }}"
          
      - name: Push slim image to Docker Hub
        if: steps.semanticrelease.outputs.new-release-published == 'true'
        run: |
          docker push ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}:${{ env.RELEASE_VERSION }}-slim
