name: Slim Image Build

on:
  workflow_dispatch:

jobs:
  build-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: df -h
      
      - name: "node-cleanup"
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          sudo rm -rf ~/.cache/
          sudo apt-get clean
      
      - run: df -h

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_REPO }}" >> $GITHUB_ENV
          echo "DOCKERHUB_IMG=${{ vars.DOCKERHUB_IMG }}" >> $GITHUB_ENV
          echo "HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF##refs/heads/}" | sed 's/\//-/g' >> $GITHUB_ENV

      - name: Build base image
        uses: docker/bake-action@v2
        with:
          push: false
          load: true
          set: |
            *.args.DOCKERHUB_REPO=${{ env.DOCKERHUB_REPO }}
            *.args.DOCKERHUB_IMG=${{ env.DOCKERHUB_IMG }}
            *.args.RELEASE_VERSION=${{ env.RELEASE_VERSION }}
            *.args.HUGGINGFACE_ACCESS_TOKEN=${{ env.HUGGINGFACE_ACCESS_TOKEN }}
          targets: base

      - name: Run DockerSlim to optimize image
        id: slim
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
          DSLIM_CONTINUE_AFTER: 10
          DSLIM_EXPOSE: 8188
          DSLIM_RC_CMD: "/start.sh"
          DSLIM_INCLUDE_PATH: "/comfyui,/opt/venv,/usr/lib/python3.11,/usr/lib/python3,/usr/local/lib/python3.11,/start.sh,/restore_snapshot.sh,/rp_handler.py,/test_input.json,/extra_model_paths.yaml,/models"
          DSLIM_INCLUDE_SHELL: true
          DSLIM_INCLUDE_ZONEINFO: true
          DSLIM_RM_FILE_ARTIFACTS: true
          DSLIM_SHOW_BLOGS: true
          DSLIM_SHOW_CLOGS: true
        with:
          target: ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}:${{ env.RELEASE_VERSION }}-base
          tag: "slim"

      - name: Show report
        run: |
          echo "Slim build report:"
          echo "${{ steps.slim.outputs.report }}"
          
      - name: Push slim image to Docker Hub
        run: |
          docker push ${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}:${{ env.RELEASE_VERSION }}-slim